In [2]:
import operator
import psycopg2 as pg
import pandas as pd
import pandas.io.sql as pd_sql
import numpy as np

# visualization imports
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')

%matplotlib inline

# modelling imports
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, accuracy_score, roc_auc_score, roc_curve, precision_recall_curve, f1_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

In [3]:
# Postgres info to connect

connection_args = {
    'host': 'localhost',
    'dbname': 'nfl_db',
    'port': 5432
}

connection = pg.connect(**connection_args) # Unpacks dictionary keys and values

In [4]:
# initial preview of table

query = "SELECT * FROM nfl_plays LIMIT 10;"
pd_sql.read_sql(query, connection)

,index,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,...,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,0,46,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,...,None,None,None,0,None,None,0.0,0.0,0.0,0.0
1,1,68,2009091000,PIT,TEN,PIT,home,TEN,PIT,58.0,...,None,None,None,0,None,None,0.0,0.0,0.0,0.0
2,2,92,2009091000,PIT,TEN,PIT,home,TEN,PIT,53.0,...,None,None,None,0,None,None,0.0,0.0,0.0,0.0
3,3,113,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,...,None,None,None,0,None,None,0.0,0.0,0.0,0.0
4,4,139,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,...,None,None,None,0,None,None,0.0,0.0,0.0,0.0
5,5,162,2009091000,PIT,TEN,TEN,away,PIT,TEN,98.0,...,None,None,None,0,None,None,0.0,0.0,0.0,0.0
6,6,183,2009091000,PIT,TEN,TEN,away,PIT,TEN,98.0,...,None,None,None,0,None,None,0.0,0.0,0.0,0.0
7,7,207,2009091000,PIT,TEN,TEN,away,PIT,TEN,94.0,...,None,None,None,0,None,None,0.0,0.0,0.0,0.0
8,8,228,2009091000,PIT,TEN,TEN,away,PIT,TEN,96.0,...,None,None,None,0,None,None,0.0,0.0,0.0,0.0
9,9,253,2009091000,PIT,TEN,PIT,home,TEN,TEN,43.0,...,None,None,None,0,None,None,0.0,0.0,0.0,0.0

In [5]:
# find information on all columns

query = "SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'nfl_plays';"
pd_sql.read_sql(query, connection)

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,nfl_db,public,nfl_plays,index,1,None,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,nfl_db,public,nfl_plays,play_id,2,None,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,nfl_db,public,nfl_plays,game_id,3,None,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,nfl_db,public,nfl_plays,home_team,4,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,nfl_db,public,nfl_plays,away_team,5,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
5,nfl_db,public,nfl_plays,posteam,6,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
6,nfl_db,public,nfl_plays,posteam_type,7,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
7,nfl_db,public,nfl_plays,defteam,8,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
8,nfl_db,public,nfl_plays,side_of_field,9,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
9,nfl_db,public,nfl_plays,yardline_100,10,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
10,nfl_db,public,nfl_plays,game_date,11,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
11,nfl_db,public,nfl_plays,quarter_seconds_remaining,12,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
12,nfl_db,public,nfl_plays,half_seconds_remaining,13,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
13,nfl_db,public,nfl_plays,game_seconds_remaining,14,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
14,nfl_db,public,nfl_plays,game_half,15,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
15,nfl_db,public,nfl_plays,quarter_end,16,None,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
16,nfl_db,public,nfl_plays,drive,17,None,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
17,nfl_db,public,nfl_plays,sp,18,None,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
18,nfl_db,public,nfl_plays,qtr,19,None,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
19,nfl_db,public,nfl_plays,down,20,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
20,nfl_db,public,nfl_plays,goal_to_go,21,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
21,nfl_db,public,nfl_plays,time,22,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
22,nfl_db,public,nfl_plays,yrdln,23,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
23,nfl_db,public,nfl_plays,ydstogo,24,None,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
24,nfl_db,public,nfl_plays,ydsnet,25,None,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
25,nfl_db,public,nfl_plays,description,26,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
26,nfl_db,public,nfl_plays,play_type,27,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
27,nfl_db,public,nfl_plays,yards_gained,28,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
28,nfl_db,public,nfl_plays,shotgun,29,None,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
29,nfl_db,public,nfl_plays,no_huddle,30,None,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,nfl_db,public,nfl_plays,pass_defense_1_player_name,227,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
227,nfl_db,public,nfl_plays,pass_defense_2_player_id,228,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
228,nfl_db,public,nfl_plays,pass_defense_2_player_name,229,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
229,nfl_db,public,nfl_plays,fumbled_1_team,230,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
230,nfl_db,public,nfl_plays,fumbled_1_player_id,231,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
231,nfl_db,public,nfl_plays,fumbled_1_player_name,232,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
232,nfl_db,public,nfl_plays,fumbled_2_player_id,233,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
233,nfl_db,public,nfl_plays,fumbled_2_player_name,234,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
234,nfl_db,public,nfl_plays,fumbled_2_team,235,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
235,nfl_db,public,nfl_plays,fumble_recovery_1_team,236,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
236,nfl_db,public,nfl_plays,fumble_recovery_1_yards,237,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
237,nfl_db,public,nfl_plays,fumble_recovery_1_player_id,238,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
238,nfl_db,public,nfl_plays,fumble_recovery_1_player_name,239,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
239,nfl_db,public,nfl_plays,fumble_recovery_2_team,240,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
240,nfl_db,public,nfl_plays,fumble_recovery_2_yards,241,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
241,nfl_db,public,nfl_plays,fumble_recovery_2_player_id,242,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
242,nfl_db,public,nfl_plays,fumble_recovery_2_player_name,243,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
243,nfl_db,public,nfl_plays,return_team,244,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
244,nfl_db,public,nfl_plays,return_yards,245,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
245,nfl_db,public,nfl_plays,penalty_team,246,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
246,nfl_db,public,nfl_plays,penalty_player_id,247,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
247,nfl_db,public,nfl_plays,penalty_player_name,248,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
248,nfl_db,public,nfl_plays,penalty_yards,249,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
249,nfl_db,public,nfl_plays,replay_or_challenge,250,None,YES,bigint,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
250,nfl_db,public,nfl_plays,replay_or_challenge_result,251,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
251,nfl_db,public,nfl_plays,penalty_type,252,None,YES,text,None,1.073742e+09,...,NO,None,None,None,None,None,NO,NEVER,None,YES
252,nfl_db,public,nfl_plays,defensive_two_point_attempt,253,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
253,nfl_db,public,nfl_plays,defensive_two_point_conv,254,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
254,nfl_db,public,nfl_plays,defensive_extra_point_attempt,255,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
255,nfl_db,public,nfl_plays,defensive_extra_point_conv,256,None,YES,double precision,None,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [6]:
# check play_types of plays with negative yards gained

query = "SELECT play_type, COUNT(*) FROM nfl_plays WHERE yards_gained < 0 GROUP BY play_type;"

pd_sql.read_sql(query, connection)

  play_type  count
0      pass  13988
1      punt      1
2  qb_kneel   3588
3       run  13157

In [7]:
# check yard loss play details **NEED TO RENAME COLUMN 'desc' TO 'description'**

query = "SELECT game_date, qtr, time, home_team, description, play_type, yards_gained, yardline_100\
        FROM nfl_plays WHERE yards_gained < 0 AND game_date > '2018-11-01' ORDER BY yards_gained ASC LIMIT 20;"

pd.set_option('display.max_colwidth', -1)
pd_sql.read_sql(query, connection)

,game_date,qtr,time,home_team,description,play_type,yards_gained,yardline_100
0,2018-12-02,4,08:26:00,DET,"(8:26) M.Stafford sacked at DET 29 for -13 yards (A.Donald). FUMBLES (A.Donald) [A.Donald], RECOVERED by LA-S.Ebukam at DET 24. S.Ebukam to DET 24 for no gain (L.Toilolo).",pass,-18.0,58.0
1,2018-12-16,4,00:24:00,CHI,"(:24) (Shotgun) A.Rodgers sacked at CHI 27 for -18 yards (L.Floyd). Penalty on GB, Illegal Shift, declined.",pass,-18.0,9.0
2,2018-12-09,1,01:34:00,GB,"(1:34) (Shotgun) M.Ryan sacked at GB 26 for -7 yards. FUMBLES, recovered by ATL-T.Coleman at GB 35. T.Coleman to GB 35 for no gain (J.Alexander).",pass,-16.0,19.0
3,2018-11-19,3,13:38:00,LA,"(13:38) (Shotgun) P.Mahomes sacked at LA 36 for -11 yards (A.Donald). FUMBLES (A.Donald) [A.Donald], touched at LA 41, RECOVERED by LA-J.Franklin at KC 46. J.Franklin to KC 46 for no gain (A.Reiter).",pass,-16.0,25.0
4,2018-12-02,4,09:20:00,SEA,(9:20) G.Fant reported in as eligible. R.Wilson sacked at SF 17 for -16 yards (R.Blair).,pass,-16.0,1.0
5,2018-11-11,4,06:08:00,LA,"(6:08) (Shotgun) R.Wilson sacked at SEA 23 for -9 yards (D.Fowler). FUMBLES (D.Fowler), touched at SEA 17, RECOVERED by LA-D.Fowler at SEA 9. D.Fowler to SEA 9 for no gain (J.Simmons).",pass,-15.0,68.0
6,2018-11-11,2,11:20:00,OAK,"(11:20) (Shotgun) D.Carr sacked at LAC 30 for -9 yards (M.Ingram). FUMBLES (M.Ingram) [M.Ingram], RECOVERED by LAC-C.Liuget at LAC 36. C.Liuget to OAK 40 for 24 yards (J.Richard). 4-yards loose ball yardage.",pass,-15.0,21.0
7,2018-11-11,4,06:08:00,LA,"(6:08) (Shotgun) R.Wilson sacked at SEA 23 for -9 yards (D.Fowler). FUMBLES (D.Fowler), touched at SEA 17, RECOVERED by LA-D.Fowler at SEA 9. D.Fowler to SEA 9 for no gain (J.Simmons).",pass,-15.0,68.0
8,2018-11-11,2,11:20:00,OAK,"(11:20) (Shotgun) D.Carr sacked at LAC 30 for -9 yards (M.Ingram). FUMBLES (M.Ingram) [M.Ingram], RECOVERED by LAC-C.Liuget at LAC 36. C.Liuget to OAK 40 for 24 yards (J.Richard). 4-yards loose ball yardage.",pass,-15.0,21.0
9,2018-12-15,4,13:18:00,NYJ,(13:18) (Shotgun) D.Watson sacked at NYJ 31 for -14 yards (J.Adams).,pass,-14.0,17.0
10,2018-12-09,2,11:33:00,WAS,(11:33) (Shotgun) E.Manning sacked at WAS 17 for -14 yards (R.Kerrigan).,pass,-14.0,3.0
11,2018-11-11,2,02:36:00,KC,"(2:36) (Shotgun) J.Rosen sacked at KC 43 for -7 yards (C.Jones). FUMBLES (C.Jones) [C.Jones], touched at 50, recovered by ARI-M.Cole at ARI 47. M.Cole to ARI 47 for no gain (D.Ford).",pass,-14.0,36.0
12,2018-11-11,2,02:36:00,KC,"(2:36) (Shotgun) J.Rosen sacked at KC 43 for -7 yards (C.Jones). FUMBLES (C.Jones) [C.Jones], touched at 50, recovered by ARI-M.Cole at ARI 47. M.Cole to ARI 47 for no gain (D.Ford).",pass,-14.0,36.0
13,2018-12-09,4,06:30:00,TB,(6:30) (Shotgun) J.Winston sacked at TB 28 for -14 yards (S.Rankins).,pass,-14.0,58.0
14,2018-12-06,4,03:33:00,TEN,(3:33) (Shotgun) C.Kessler sacked at JAX 31 for -14 yards (L.Ryan).,pass,-14.0,55.0
15,2018-11-11,2,01:12:00,PHI,(1:12) (Shotgun) D.Prescott sacked at DAL 27 for -13 yards (sack split by B.Graham and C.Long).,pass,-13.0,60.0
16,2018-11-11,2,01:12:00,PHI,(1:12) (Shotgun) D.Prescott sacked at DAL 27 for -13 yards (sack split by B.Graham and C.Long).,pass,-13.0,60.0
17,2018-11-04,2,09:50:00,CAR,(9:50) (Shotgun) R.Fitzpatrick sacked at TB 6 for -13 yards (M.Addison).,pass,-13.0,81.0
18,2018-11-04,2,14:10:00,SEA,(14:10) (Shotgun) G.Fant reported in as eligible. R.Wilson sacked at SEA 14 for -13 yards (J.Addae).,pass,-13.0,73.0
19,2018-12-15,1,10:15:00,NYJ,(10:15) (Shotgun) D.Watson sacked at NYJ 22 for -13 yards (H.Anderson).,pass,-13.0,9.0

In [8]:
# check play_types of plays with zero yards gained

query = "SELECT play_type, COUNT(*) FROM nfl_plays WHERE yards_gained = 0 GROUP BY play_type;"

pd_sql.read_sql(query, connection)

     play_type  count
0  extra_point  10934
1  field_goal   9777
2  kickoff      25552
3  no_play      42417
4  pass         67832
5  punt         23913
6  qb_kneel     235
7  qb_spike     690
8  run          12391
9  None         12874

In [9]:
# check play_types of plays with positive yards gained

query = "SELECT play_type, COUNT(*) FROM nfl_plays WHERE yards_gained > 0 GROUP BY play_type;"

pd_sql.read_sql(query, connection)

  play_type   count
0  no_play   14
1  pass      104753
2  qb_kneel  4
3  run       107038

In [10]:
# create dataframe from selected columns

query = "SELECT play_id, game_date, yards_gained, play_type, home_team, away_team, posteam, \
        posteam_type, ydsnet, yardline_100, quarter_seconds_remaining, qtr, down, goal_to_go, \
        ydstogo, shotgun, no_huddle, qb_dropback, qb_kneel, qb_spike, qb_scramble \
        FROM nfl_plays \
        WHERE play_type IN ('pass','run');"

df = pd_sql.read_sql(query, connection)

In [11]:
df.head()

,play_id,game_date,yards_gained,play_type,home_team,away_team,posteam,posteam_type,ydsnet,yardline_100,...,qtr,down,goal_to_go,ydstogo,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble
0,68,2009-09-10,5.0,pass,PIT,TEN,PIT,home,5,58.0,...,1,1.0,0.0,10,0,0,1.0,0,0,0
1,92,2009-09-10,-3.0,run,PIT,TEN,PIT,home,2,53.0,...,1,2.0,0.0,5,0,0,0.0,0,0,0
2,113,2009-09-10,0.0,pass,PIT,TEN,PIT,home,2,56.0,...,1,3.0,0.0,8,1,0,1.0,0,0,0
3,162,2009-09-10,0.0,run,PIT,TEN,TEN,away,0,98.0,...,1,1.0,0.0,10,0,0,0.0,0,0,0
4,183,2009-09-10,4.0,pass,PIT,TEN,TEN,away,4,98.0,...,1,2.0,0.0,10,0,0,1.0,0,0,0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319369 entries, 0 to 319368
Data columns (total 21 columns):
play_id                      319369 non-null int64
game_date                    319369 non-null object
yards_gained                 319159 non-null float64
play_type                    319369 non-null object
home_team                    319369 non-null object
away_team                    319369 non-null object
posteam                      319369 non-null object
posteam_type                 319369 non-null object
ydsnet                       319369 non-null int64
yardline_100                 319369 non-null float64
quarter_seconds_remaining    319369 non-null float64
qtr                          319369 non-null int64
down                         318691 non-null float64
goal_to_go                   319369 non-null float64
ydstogo                      319369 non-null int64
shotgun                      319369 non-null int64
no_huddle                    319369 non-null int64
qb_dropback                  319369 non-null float64
qb_kneel                     319369 non-null int64
qb_spike                     319369 non-null int64
qb_scramble                  319369 non-null int64
dtypes: float64(6), int64(9), object(6)
memory usage: 51.2+ MB

In [13]:
# count how many rows have NaNs

df1 = df[df.isnull().any(axis=1)]
df1

,play_id,game_date,yards_gained,play_type,home_team,away_team,posteam,posteam_type,ydsnet,yardline_100,...,qtr,down,goal_to_go,ydstogo,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble
720,2996,2009-09-13,0.0,run,IND,JAC,JAC,away,58,2.0,...,4,NaN,0.0,0,0,0,0.0,0,0,0
855,3721,2009-09-13,0.0,pass,CIN,DEN,DEN,away,87,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
1709,3768,2009-09-13,2.0,pass,GB,CHI,GB,home,72,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
1828,3778,2009-09-14,0.0,pass,NE,BUF,NE,home,81,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
1832,3918,2009-09-14,0.0,pass,NE,BUF,NE,home,31,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
3335,4425,2009-09-20,0.0,pass,BUF,TB,TB,away,80,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
4312,3658,2009-09-27,0.0,pass,DET,WAS,DET,home,85,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
5289,3885,2009-09-27,2.0,pass,SEA,CHI,CHI,away,71,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
5396,3079,2009-09-27,0.0,pass,CIN,PIT,CIN,home,85,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
5417,3730,2009-09-27,2.0,pass,CIN,PIT,CIN,home,71,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
6540,3076,2009-10-04,0.0,pass,JAC,TEN,TEN,away,80,2.0,...,3,NaN,0.0,0,0,0,1.0,0,0,0
6565,3786,2009-10-04,2.0,run,JAC,TEN,TEN,away,77,2.0,...,4,NaN,0.0,0,0,0,0.0,0,0,0
6682,3418,2009-10-04,0.0,run,KC,NYG,KC,home,48,3.0,...,4,NaN,0.0,0,0,0,0.0,0,0,0
7658,3571,2009-10-05,0.0,pass,MIN,GB,GB,away,96,1.0,...,4,NaN,1.0,0,0,0,1.0,0,0,0
8262,3229,2009-10-11,2.0,pass,CAR,WAS,CAR,home,12,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
12889,3080,2009-11-01,2.0,pass,BUF,HOU,HOU,away,72,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
13263,3018,2009-11-01,2.0,pass,DET,STL,DET,home,82,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
13392,3286,2009-11-01,0.0,pass,IND,SF,IND,home,70,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
13635,3114,2009-11-01,0.0,pass,NYJ,MIA,NYJ,home,74,2.0,...,3,NaN,0.0,0,0,0,1.0,0,0,0
13649,3499,2009-11-01,0.0,pass,NYJ,MIA,MIA,away,67,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
13656,3702,2009-11-01,0.0,pass,NYJ,MIA,NYJ,home,81,7.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
14117,3222,2009-11-01,0.0,pass,GB,MIN,GB,home,74,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
14906,3856,2009-11-08,2.0,pass,JAC,KC,KC,away,68,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
14998,2869,2009-11-08,2.0,pass,NE,MIA,NE,home,80,2.0,...,3,NaN,0.0,0,0,0,1.0,0,0,0
15142,3139,2009-11-08,0.0,pass,TB,GB,TB,home,17,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
15158,3575,2009-11-08,2.0,pass,TB,GB,TB,home,72,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
15394,3157,2009-11-08,0.0,pass,SEA,DET,SEA,home,68,2.0,...,3,NaN,0.0,0,0,0,1.0,0,0,0
16123,2934,2009-11-15,0.0,pass,CAR,ATL,ATL,away,59,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
16509,3451,2009-11-15,0.0,pass,STL,NO,STL,home,80,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
16545,641,2009-11-15,0.0,pass,PIT,CIN,CIN,away,0,2.0,...,1,NaN,0.0,0,0,0,1.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310595,3078,2018-11-18,0.0,pass,JAX,PIT,PIT,away,79,2.0,...,3,NaN,0.0,0,0,0,1.0,0,0,0
310995,3944,2018-11-18,0.0,pass,DET,CAR,CAR,away,75,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
311094,3323,2018-11-18,0.0,run,LAC,DEN,DEN,away,73,2.0,...,4,NaN,0.0,0,0,0,0.0,0,0,0
311397,1355,2018-11-18,2.0,pass,CHI,MIN,CHI,home,82,2.0,...,2,NaN,0.0,0,0,0,1.0,0,0,0
311467,3923,2018-11-18,2.0,pass,CHI,MIN,MIN,away,74,1.0,...,4,NaN,1.0,0,0,0,1.0,0,0,0
311486,4574,2018-11-18,0.0,pass,CHI,MIN,MIN,away,75,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
311684,1946,2018-11-22,0.0,pass,DET,CHI,CHI,away,65,2.0,...,2,NaN,0.0,0,0,0,1.0,0,0,0
311715,2948,2018-11-22,0.0,pass,DET,CHI,DET,home,80,2.0,...,3,NaN,0.0,0,0,0,1.0,0,0,0
312737,288,2018-11-25,0.0,pass,PHI,NYG,NYG,away,75,1.0,...,1,NaN,1.0,0,0,0,1.0,0,0,0
312782,1927,2018-11-25,2.0,run,PHI,NYG,PHI,home,75,2.0,...,2,NaN,0.0,0,0,0,0.0,0,0,0
312827,3439,2018-11-25,2.0,run,PHI,NYG,PHI,home,61,2.0,...,4,NaN,0.0,0,0,0,0.0,0,0,0
313650,4148,2018-12-02,0.0,pass,ATL,BAL,ATL,home,75,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
314015,3307,2018-12-02,2.0,pass,MIA,BUF,BUF,away,83,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
314278,4053,2018-12-02,0.0,pass,HOU,CLE,CLE,away,75,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
314748,3088,2018-12-02,0.0,run,OAK,KC,OAK,home,68,2.0,...,3,NaN,0.0,0,0,0,0.0,0,0,0
315005,3341,2018-12-02,0.0,run,SEA,SF,SF,away,75,2.0,...,4,NaN,0.0,0,0,0,0.0,0,0,0
315255,2813,2018-12-02,2.0,pass,PIT,LAC,LAC,away,88,2.0,...,3,NaN,0.0,0,0,0,1.0,0,0,0
315376,2985,2018-12-03,2.0,pass,PHI,WAS,PHI,home,85,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
315743,3357,2018-12-09,2.0,pass,WAS,NYG,WAS,home,33,7.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
315749,3603,2018-12-09,2.0,pass,WAS,NYG,WAS,home,77,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
315849,2816,2018-12-09,2.0,run,TB,NO,NO,away,30,2.0,...,3,NaN,0.0,0,0,0,0.0,0,0,0
316723,2013,2018-12-09,0.0,pass,LAC,CIN,CIN,away,35,2.0,...,2,NaN,0.0,0,0,0,1.0,0,0,0
316778,3801,2018-12-09,0.0,pass,LAC,CIN,CIN,away,79,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
317399,3591,2018-12-10,2.0,pass,SEA,MIN,SEA,home,63,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
317528,4343,2018-12-13,2.0,pass,KC,LAC,LAC,away,60,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0
317857,2786,2018-12-16,2.0,pass,CHI,GB,GB,away,50,2.0,...,3,NaN,0.0,0,0,0,1.0,0,0,0
317935,1020,2018-12-16,0.0,pass,BUF,DET,DET,away,75,15.0,...,2,NaN,0.0,0,0,0,1.0,0,0,0
318056,1136,2018-12-16,0.0,run,BAL,TB,TB,away,51,15.0,...,2,NaN,0.0,0,0,0,0.0,0,0,0
318206,2332,2018-12-16,0.0,pass,ATL,ARI,ATL,home,71,2.0,...,2,NaN,0.0,0,0,0,1.0,0,0,0
319342,3239,2018-12-17,0.0,pass,CAR,NO,NO,away,84,2.0,...,4,NaN,0.0,0,0,0,1.0,0,0,0

In [14]:
# 888 out of 319,369 observations have null values, or less than 0.3%
# removing any NaN observations

df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 318481 entries, 0 to 319368
Data columns (total 21 columns):
play_id                      318481 non-null int64
game_date                    318481 non-null object
yards_gained                 318481 non-null float64
play_type                    318481 non-null object
home_team                    318481 non-null object
away_team                    318481 non-null object
posteam                      318481 non-null object
posteam_type                 318481 non-null object
ydsnet                       318481 non-null int64
yardline_100                 318481 non-null float64
quarter_seconds_remaining    318481 non-null float64
qtr                          318481 non-null int64
down                         318481 non-null float64
goal_to_go                   318481 non-null float64
ydstogo                      318481 non-null int64
shotgun                      318481 non-null int64
no_huddle                    318481 non-null int64
qb_dropback                  318481 non-null float64
qb_kneel                     318481 non-null int64
qb_spike                     318481 non-null int64
qb_scramble                  318481 non-null int64
dtypes: float64(6), int64(9), object(6)
memory usage: 53.5+ MB

In [15]:
# create binary column for if a play is a pass or a run

df['passing'] = df['play_type'].apply(lambda x: 1 if x == 'pass' else 0) 
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 318481 entries, 0 to 319368
Data columns (total 22 columns):
play_id                      318481 non-null int64
game_date                    318481 non-null object
yards_gained                 318481 non-null float64
play_type                    318481 non-null object
home_team                    318481 non-null object
away_team                    318481 non-null object
posteam                      318481 non-null object
posteam_type                 318481 non-null object
ydsnet                       318481 non-null int64
yardline_100                 318481 non-null float64
quarter_seconds_remaining    318481 non-null float64
qtr                          318481 non-null int64
down                         318481 non-null float64
goal_to_go                   318481 non-null float64
ydstogo                      318481 non-null int64
shotgun                      318481 non-null int64
no_huddle                    318481 non-null int64
qb_dropback                  318481 non-null float64
qb_kneel                     318481 non-null int64
qb_spike                     318481 non-null int64
qb_scramble                  318481 non-null int64
passing                      318481 non-null int64
dtypes: float64(6), int64(10), object(6)
memory usage: 55.9+ MB

In [15]:
# we have a large dataset, what if we only look at the Cowboys' plays?

print (len(df[df['posteam'] == 'DAL']))

9891

In [16]:
# create Cowboys dataframe from selected columns

query = "SELECT play_id, game_date, yards_gained, play_type, home_team, posteam, posteam_type,\
        ydsnet, yardline_100, quarter_seconds_remaining, qtr, down, goal_to_go, \
        ydstogo, shotgun, no_huddle, qb_dropback, qb_kneel, qb_spike, qb_scramble \
        FROM nfl_plays \
        WHERE play_type IN ('pass','run') \
        AND posteam = 'DAL';"

df_cowboys = pd_sql.read_sql(query, connection)

In [17]:
df_cowboys.head()

,play_id,game_date,yards_gained,play_type,home_team,posteam,posteam_type,ydsnet,yardline_100,quarter_seconds_remaining,qtr,down,goal_to_go,ydstogo,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble
0,58,2009-09-13,-1.0,run,TB,DAL,away,-1,64.0,892.0,1,1.0,0.0,10,0,0,0.0,0,0,0
1,79,2009-09-13,7.0,pass,TB,DAL,away,6,65.0,861.0,1,2.0,0.0,11,1,1,1.0,0,0,0
2,103,2009-09-13,7.0,run,TB,DAL,away,13,58.0,816.0,1,3.0,0.0,4,0,0,0.0,0,0,0
3,124,2009-09-13,13.0,pass,TB,DAL,away,26,51.0,772.0,1,1.0,0.0,10,0,0,1.0,0,0,0
4,148,2009-09-13,12.0,run,TB,DAL,away,38,38.0,737.0,1,1.0,0.0,10,0,0,0.0,0,0,0

In [18]:
# create binary for if Cowboys are the home team

df_cowboys['cowboys_home'] = df_cowboys['home_team'].apply(lambda x: 1 if x == 'DAL' else 0)
df_cowboys.head()

,play_id,game_date,yards_gained,play_type,home_team,posteam,posteam_type,ydsnet,yardline_100,quarter_seconds_remaining,...,down,goal_to_go,ydstogo,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,cowboys_home
0,58,2009-09-13,-1.0,run,TB,DAL,away,-1,64.0,892.0,...,1.0,0.0,10,0,0,0.0,0,0,0,0
1,79,2009-09-13,7.0,pass,TB,DAL,away,6,65.0,861.0,...,2.0,0.0,11,1,1,1.0,0,0,0,0
2,103,2009-09-13,7.0,run,TB,DAL,away,13,58.0,816.0,...,3.0,0.0,4,0,0,0.0,0,0,0,0
3,124,2009-09-13,13.0,pass,TB,DAL,away,26,51.0,772.0,...,1.0,0.0,10,0,0,1.0,0,0,0,0
4,148,2009-09-13,12.0,run,TB,DAL,away,38,38.0,737.0,...,1.0,0.0,10,0,0,0.0,0,0,0,0

In [ ]:
# create binary for if the play is a pass

df_cowboys['passing'] = df_cowboys['play_type'].apply(lambda x: 1 if x == 'pass' else 0) 
df_cowboys.head()

,play_id,game_date,yards_gained,play_type,home_team,posteam,posteam_type,ydsnet,yardline_100,quarter_seconds_remaining,...,goal_to_go,ydstogo,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,cowboys_home,passing
0,58,2009-09-13,-1.0,run,TB,DAL,away,-1,64.0,892.0,...,0.0,10,0,0,0.0,0,0,0,0,0
1,79,2009-09-13,7.0,pass,TB,DAL,away,6,65.0,861.0,...,0.0,11,1,1,1.0,0,0,0,0,1
2,103,2009-09-13,7.0,run,TB,DAL,away,13,58.0,816.0,...,0.0,4,0,0,0.0,0,0,0,0,0
3,124,2009-09-13,13.0,pass,TB,DAL,away,26,51.0,772.0,...,0.0,10,0,0,1.0,0,0,0,0,1
4,148,2009-09-13,12.0,run,TB,DAL,away,38,38.0,737.0,...,0.0,10,0,0,0.0,0,0,0,0,0

In [ ]:
# create y for if the yards_gained were positive or not

df_cowboys['yards_g_l'] = df_cowboys['yards_gained'].apply(lambda x: 'gain' if x > 0 else 'loss')
df_cowboys.head()

,play_id,game_date,yards_gained,play_type,home_team,posteam,posteam_type,ydsnet,yardline_100,quarter_seconds_remaining,...,ydstogo,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,cowboys_home,passing,yards_g_l
0,58,2009-09-13,-1.0,run,TB,DAL,away,-1,64.0,892.0,...,10,0,0,0.0,0,0,0,0,0,loss
1,79,2009-09-13,7.0,pass,TB,DAL,away,6,65.0,861.0,...,11,1,1,1.0,0,0,0,0,1,gain
2,103,2009-09-13,7.0,run,TB,DAL,away,13,58.0,816.0,...,4,0,0,0.0,0,0,0,0,0,gain
3,124,2009-09-13,13.0,pass,TB,DAL,away,26,51.0,772.0,...,10,0,0,1.0,0,0,0,0,1,gain
4,148,2009-09-13,12.0,run,TB,DAL,away,38,38.0,737.0,...,10,0,0,0.0,0,0,0,0,0,gain

In [ ]:
df_cowboys.dropna(inplace=True)
df_cowboys.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9891 entries, 0 to 9906
Data columns (total 23 columns):
play_id                      9891 non-null int64
game_date                    9891 non-null object
yards_gained                 9891 non-null float64
play_type                    9891 non-null object
home_team                    9891 non-null object
posteam                      9891 non-null object
posteam_type                 9891 non-null object
ydsnet                       9891 non-null int64
yardline_100                 9891 non-null float64
quarter_seconds_remaining    9891 non-null float64
qtr                          9891 non-null int64
down                         9891 non-null float64
goal_to_go                   9891 non-null float64
ydstogo                      9891 non-null int64
shotgun                      9891 non-null int64
no_huddle                    9891 non-null int64
qb_dropback                  9891 non-null float64
qb_kneel                     9891 non-null int64
qb_spike                     9891 non-null int64
qb_scramble                  9891 non-null int64
cowboys_home                 9891 non-null int64
passing                      9891 non-null int64
yards_g_l                    9891 non-null object
dtypes: float64(6), int64(11), object(6)
memory usage: 1.8+ MB

In [ ]:
df_cowboys.columns

Index(['play_id', 'game_date', 'yards_gained', 'play_type', 'home_team',
       'posteam', 'posteam_type', 'ydsnet', 'yardline_100',
       'quarter_seconds_remaining', 'qtr', 'down', 'goal_to_go', 'ydstogo',
       'shotgun', 'no_huddle', 'qb_dropback', 'qb_kneel', 'qb_spike',
       'qb_scramble', 'cowboys_home', 'passing', 'yards_g_l'],
      dtype='object')

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df_cowboys.iloc[:, 7:22], df_cowboys.iloc[:, 22], 
                                                    test_size = 0.2, random_state=33)

In [ ]:
y_test_binary = y_test.apply(lambda x: 1 if x == 'gain' else 0)
y_test_binary.head()

3946    1
7248    1
2457    1
9109    1
2288    1
Name: yards_g_l, dtype: int64

In [ ]:
df_cowboys.groupby('yards_g_l').count()
# ratio of yards gain to yards loss is 69.4% to 30.6%
# model needs to have a score better than 69.4%

,play_id,game_date,yards_gained,play_type,home_team,posteam,posteam_type,ydsnet,yardline_100,quarter_seconds_remaining,...,goal_to_go,ydstogo,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,cowboys_home,passing
yards_g_l,,,,,,,,,,,,,,,,,,,,,
gain,6862,6862,6862,6862,6862,6862,6862,6862,6862,6862,...,6862,6862,6862,6862,6862,6862,6862,6862,6862,6862
loss,3029,3029,3029,3029,3029,3029,3029,3029,3029,3029,...,3029,3029,3029,3029,3029,3029,3029,3029,3029,3029

In [ ]:
train_df = X_train.copy()
train_df['yards_g_l'] = y_train

train_df.head()

,ydsnet,yardline_100,quarter_seconds_remaining,qtr,down,goal_to_go,ydstogo,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,cowboys_home,passing,yards_g_l
9260,47,75.0,451.0,3,1.0,0.0,10,0,0,0.0,0,0,0,1,0,gain
6183,48,28.0,561.0,1,1.0,0.0,10,0,0,0.0,0,0,0,1,0,loss
5936,47,43.0,619.0,4,3.0,0.0,6,1,0,1.0,0,0,0,1,1,gain
3798,1,54.0,107.0,4,2.0,0.0,9,0,0,0.0,0,0,0,1,0,loss
6520,17,59.0,66.0,2,2.0,0.0,5,1,0,1.0,0,0,0,0,1,loss

In [ ]:
sns.pairplot(train_df, hue='yards_g_l', plot_kws={'alpha': 0.1});

/anaconda3/lib/python3.7/site-packages/statsmodels/nonparametric/kde.py:488: RuntimeWarning: invalid value encountered in true_divide
  binned = fast_linbin(X, a, b, gridsize) / (delta * nobs)
/anaconda3/lib/python3.7/site-packages/statsmodels/nonparametric/kdetools.py:34: RuntimeWarning: invalid value encountered in double_scalars
  FAC1 = 2*(np.pi*bw/RANGE)**2
/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

In [ ]:
std_scale = StandardScaler()

X_train_scaled = std_scale.fit_transform(X_train)
X_test_scaled = std_scale.fit_transform(X_test)

## Logistic Regression

In [ ]:
model_lr = LogisticRegression(random_state = 22)
model_lr.fit(X_train, y_train)

In [ ]:
model_lr.score(X_test, y_test)

In [ ]:
labels = ['loss','gain']

cm_lr = confusion_matrix(y_test, model_lr.predict(X_test), labels)

fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111)
sns.heatmap(cm_lr, annot=True, fmt='g').set_title('Logistic Regression Confusion Matrix')
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)
plt.xlabel('Predicted')
plt.ylabel('Truth');

In [ ]:
model_lr_scaled = LogisticRegression(random_state = 12)
model_lr_scaled.fit(X_train_scaled, y_train)

In [ ]:
model_lr_scaled.score(X_test_scaled, y_test)

In [ ]:
cm_lr_scaled = confusion_matrix(y_test, model_lr_scaled.predict(X_test_scaled), labels)

fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111)
sns.heatmap(cm_lr_scaled, annot=True, fmt='g').set_title('Logistic Regression Scaled Confusion Matrix')
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)
plt.xlabel('Predicted')
plt.ylabel('Truth');

In [ ]:
print(classification_report(y_test, model_lr_scaled.predict(X_test_scaled), labels))

In [ ]:
fpr, tpr, thresholds = roc_curve(y_test_binary, model_lr_scaled.predict_proba(X_test_scaled)[:,0])

plt.plot(fpr, tpr,lw=2)
plt.plot([0,1],[0,1],c='violet',ls='--')
plt.xlim([-0.05,1.05])
plt.ylim([-0.05,1.05])

plt.xlabel('False positive rate')
plt.ylabel('True positive rate')
plt.title('LR ROC curve for yard gains in NFL plays');
print("ROC AUC score = ", roc_auc_score(y_test_binary, model_lr_scaled.predict_proba(X_test_scaled)[:,0]))

## KNN

In [ ]:
from sklearn import neighbors
model_knn = neighbors.KNeighborsClassifier()

In [ ]:
model_knn.fit(X_train_scaled, y_train)

In [ ]:
model_knn.score(X_test_scaled, y_test)

In [ ]:
cm_knn = confusion_matrix(y_test, model_knn.predict(X_test_scaled), labels)

fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111)
sns.heatmap(cm_knn, annot=True, fmt='g').set_title('KNN Confusion Matrix')
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)
plt.xlabel('Predicted')
plt.ylabel('Truth');

In [ ]:
print(classification_report(y_test, model_knn.predict(X_test_scaled), labels))

In [ ]:
fpr, tpr, thresholds = roc_curve(y_test_binary, model_knn.predict_proba(X_test_scaled)[:,0])

plt.plot(fpr, tpr,lw=2)
plt.plot([0,1],[0,1],c='violet',ls='--')
plt.xlim([-0.05,1.05])
plt.ylim([-0.05,1.05])

plt.xlabel('False positive rate')
plt.ylabel('True positive rate')
plt.title('KNN ROC curve for yard gains in NFL plays');
print("ROC AUC score = ", roc_auc_score(y_test_binary, model_knn.predict_proba(X_test_scaled)[:,0]))

## SVM

In [ ]:
from sklearn.svm import SVC
model_svm = SVC(random_state = 30)

In [ ]:
model_svm.fit(X_train_scaled, y_train)

In [ ]:
model_svm.score(X_test_scaled, y_test)

In [ ]:
cm_svm = confusion_matrix(y_test, model_svm.predict(X_test_scaled), labels)

fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111)
sns.heatmap(cm_svm, annot=True, fmt='g').set_title('SVM Scaled Confusion Matrix')
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)
plt.xlabel('Predicted')
plt.ylabel('Truth');

In [ ]:
'''svm_test_score = []

for i in [0.1, 1.0, 10.0, 100.0]:
    model_test = SVC(C=i, kernel='linear', random_state = 30)
    model_test.fit(X_train_scaled, y_train)
    svm_test_score.append(model_test.score(X_test_scaled, y_test))

svm_test_score'''

In [ ]:
print(classification_report(y_test, model_svm.predict(X_test_scaled), labels))

## Decision Tree

In [ ]:
from sklearn import tree

In [ ]:
model_tree = tree.DecisionTreeClassifier(max_depth=10, random_state=44)

In [ ]:
model_tree.fit(X_train_scaled, y_train)

In [ ]:
model_tree.score(X_train_scaled, y_train)

In [ ]:
model_tree.score(X_test_scaled, y_test)

In [ ]:
train_score = []
test_score = []

for i in range(1,21):
    model_test = tree.DecisionTreeClassifier(max_depth=i, random_state=44)
    model_test.fit(X_train_scaled, y_train)
    train_score.append(model_test.score(X_train_scaled, y_train))
    test_score.append(model_test.score(X_test_scaled, y_test))

In [ ]:
train_score

In [ ]:
test_score

In [ ]:
plt.plot(range(1,21), test_score, 'b', range(1,21), train_score, 'r')
plt.show()

# using max_depth of 10 gives best result on test set

In [ ]:
cm_tree = confusion_matrix(y_test, model_tree.predict(X_test_scaled), labels)

fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111)
sns.heatmap(cm_tree, annot=True, fmt='g').set_title('Decision Tree Scaled Confusion Matrix')
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)
plt.xlabel('Predicted')
plt.ylabel('Truth');

In [ ]:
print(classification_report(y_test, model_tree.predict(X_test_scaled), labels))

In [ ]:
fpr, tpr, thresholds = roc_curve(y_test_binary, model_tree.predict_proba(X_test_scaled)[:,0])

plt.plot(fpr, tpr,lw=2)
plt.plot([0,1],[0,1],c='violet',ls='--')
plt.xlim([-0.05,1.05])
plt.ylim([-0.05,1.05])

plt.xlabel('False positive rate')
plt.ylabel('True positive rate')
plt.title('ROC curve for yard gains in NFL plays');
print("ROC AUC score = ", roc_auc_score(y_test_binary, model_tree.predict_proba(X_test_scaled)[:,0]))

## Naive Bayes - Gaussian

In [ ]:
from sklearn import naive_bayes

In [ ]:
model_NB_Gaus = naive_bayes.GaussianNB()

In [ ]:
model_NB_Gaus.fit(X_train_scaled, y_train)

In [ ]:
model_NB_Gaus.score(X_test_scaled, y_test)

## Extra Trees

In [ ]:
from sklearn import ensemble

In [ ]:
model_xtrees = ensemble.ExtraTreesClassifier(n_estimators=100, random_state=15)

In [ ]:
model_xtrees.fit(X_train_scaled, y_train)

In [ ]:
model_xtrees.score(X_test_scaled, y_test)

In [ ]:
cm_xtrees = confusion_matrix(y_test, model_xtrees.predict(X_test_scaled), labels)

fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111)
sns.heatmap(cm_xtrees, annot=True, fmt='g').set_title('Extra Trees Confusion Matrix')
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)
plt.xlabel('Predicted')
plt.ylabel('Truth');

In [ ]:
print(classification_report(y_test, model_xtrees.predict(X_test_scaled), labels))

In [ ]:
fpr, tpr, thresholds = roc_curve(y_test_binary, model_xtrees.predict_proba(X_test_scaled)[:,0])

plt.plot(fpr, tpr,lw=2)
plt.plot([0,1],[0,1],c='violet',ls='--')
plt.xlim([-0.05,1.05])
plt.ylim([-0.05,1.05])

plt.xlabel('False positive rate')
plt.ylabel('True positive rate')
plt.title('ROC curve for yard gains in NFL plays');
print("ROC AUC score = ", roc_auc_score(y_test_binary, model_xtrees.predict_proba(X_test_scaled)[:,0]))

## Random Forest

In [ ]:
model_rf = ensemble.RandomForestClassifier(n_estimators=100, random_state=15)

In [ ]:
model_rf.fit(X_train_scaled, y_train)

In [ ]:
model_rf.score(X_test_scaled, y_test)

In [ ]:
cm_rf = confusion_matrix(y_test, model_rf.predict(X_test_scaled), labels)

fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111)
sns.heatmap(cm_rf, annot=True, fmt='g').set_title('Random Forest Confusion Matrix')
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)
plt.xlabel('Predicted')
plt.ylabel('Truth');

In [ ]:
print(classification_report(y_test, model_rf.predict(X_test_scaled), labels))

In [ ]:
precision_curve, recall_curve, threshold_curve = precision_recall_curve(y_test_binary, model_rf.predict_proba(X_test_scaled)[:,0] )

plt.figure(dpi=80)
plt.plot(threshold_curve, precision_curve[1:],label='precision')
plt.plot(threshold_curve, recall_curve[1:], label='recall')
plt.legend(loc='lower left')
plt.xlabel('Threshold (above this probability, label as )');
plt.title('Precision and Recall Curves');

In [ ]:
threshold = 0.46

predicted_proba = model_rf.predict_proba(X_test_scaled)
predicted = (predicted_proba [:,0] >= threshold).astype('int')

print(classification_report(y_test_binary, predicted))

In [ ]:
threshold = np.arange(.40,.60,.01)

for i in threshold:
    predicted_proba = model_rf.predict_proba(X_test_scaled)
    predicted = (predicted_proba [:,0] >= i).astype('int')

    print(f1_score(y_test_binary, predicted))

In [ ]:
fpr, tpr, thresholds = roc_curve(y_test_binary, model_rf.predict_proba(X_test_scaled)[:,0])

plt.plot(fpr, tpr,lw=2)
plt.plot([0,1],[0,1],c='violet',ls='--')
plt.xlim([-0.05,1.05])
plt.ylim([-0.05,1.05])

plt.xlabel('False positive rate')
plt.ylabel('True positive rate')
plt.title('ROC curve for yard gains in NFL plays');
print("ROC AUC score = ", roc_auc_score(y_test_binary, model_rf.predict_proba(X_test_scaled)[:,0]))

#### Random Forest - Feature Importance - sklearn default

In [ ]:
from sklearn.feature_selection import SelectFromModel

In [ ]:
sel = SelectFromModel(ensemble.RandomForestClassifier(n_estimators = 100, random_state = 15))
sel.fit(X_train_scaled, y_train)
sel.get_support()

In [ ]:
selected_feat= X_train.columns[(sel.get_support())]
print(selected_feat)

In [ ]:
importances = model_rf.feature_importances_
std = np.std([tree.feature_importances_ for tree in model_rf.estimators_],
             axis=0)
indices = np.argsort(importances)

# Plot the feature importances of the forest
plt.figure()
plt.title("Default sklearn Feature Importances")
plt.barh(range(X_train_scaled.shape[1]), importances[indices],
       color="b", xerr=std[indices], align="center")
# If you want to define your own labels,
# change indices to a list of labels on the following line.
plt.yticks(range(X_train_scaled.shape[1]), [X_train.columns[i] for i in indices])
plt.ylim([-1, X_train_scaled.shape[1]])
plt.show()

#### Random Forest - Feature Importance - rfpimp version

https://github.com/parrt/random-forest-importances

In [ ]:
from rfpimp import *

In [ ]:
model_rf2 = ensemble.RandomForestClassifier(n_estimators=100, random_state=15)
model_rf2.fit(X_train, y_train)

imp = importances(model_rf2, X_train, y_train) # permutation
viz = plot_importances(imp, width=6)
viz.view()

Top 7 features in both cases are ydsnet, yardline_100, ydstogo, quarter_seconds_remaining, qtr, down, and passing